CREATE TABLE IF NOT EXISTS people (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(64) NOT NULL,
	surname VARCHAR(64) NOT NULL,
	patronymic VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cars (
	id BIGSERIAL PRIMARY KEY,
	reg_num VARCHAR(16) UNIQUE NOT NULL,
	mark VARCHAR(32) NOT NULL,
	model VARCHAR(32) NOT NULL,
	year INTEGER,
	owner_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	FOREIGN KEY (owner_id) REFERENCES people(id)
);
